// <auto-generated />
using System;
using DoctorWho.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoctorWho.Db.Migrations
{
    [DbContext(typeof(DoctorWhoCoreDbContext))]
    [Migration("20211006124119_dto_refactor")]
    partial class dto_refactor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoctorWho.Db.DBModels.AuthorDbModel", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            AuthorName = "Ida Gibson",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 10, 23, 16, 48, 45, 723, DateTimeKind.Local).AddTicks(7137),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 20, 48, 50, 28, DateTimeKind.Local).AddTicks(2904)
                        },
                        new
                        {
                            AuthorId = 2,
                            AuthorName = "Lula Nitzsche",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 7, 5, 1, 8, 2, 314, DateTimeKind.Local).AddTicks(6354),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 7, 15, 10, 968, DateTimeKind.Local).AddTicks(6473)
                        },
                        new
                        {
                            AuthorId = 3,
                            AuthorName = "Dana Daniel",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 7, 17, 6, 5, 17, 826, DateTimeKind.Local).AddTicks(8435),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 20, 58, 22, 249, DateTimeKind.Local).AddTicks(1588)
                        },
                        new
                        {
                            AuthorId = 4,
                            AuthorName = "Lora Ernser",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 8, 10, 22, 51, 17, 137, DateTimeKind.Local).AddTicks(6277),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 1, 3, 14, 487, DateTimeKind.Local).AddTicks(7671)
                        },
                        new
                        {
                            AuthorId = 5,
                            AuthorName = "Vergie Gerhold",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 3, 18, 7, 39, 43, 474, DateTimeKind.Local).AddTicks(9863),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 2, 19, 56, 560, DateTimeKind.Local).AddTicks(3397)
                        },
                        new
                        {
                            AuthorId = 6,
                            AuthorName = "Daphney Waters",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 8, 13, 3, 45, 43, 343, DateTimeKind.Local).AddTicks(1348),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 0, 10, 36, 832, DateTimeKind.Local).AddTicks(2050)
                        },
                        new
                        {
                            AuthorId = 7,
                            AuthorName = "Bertram Bergnaum",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2019, 2, 17, 20, 39, 13, 83, DateTimeKind.Local).AddTicks(6223),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 22, 42, 30, 746, DateTimeKind.Local).AddTicks(955)
                        },
                        new
                        {
                            AuthorId = 8,
                            AuthorName = "Rubye Gusikowski",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 2, 15, 13, 45, 2, 357, DateTimeKind.Local).AddTicks(6165),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 19, 26, 24, 326, DateTimeKind.Local).AddTicks(5147)
                        },
                        new
                        {
                            AuthorId = 9,
                            AuthorName = "Mike Green",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2019, 6, 17, 12, 44, 24, 864, DateTimeKind.Local).AddTicks(944),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 22, 40, 9, 950, DateTimeKind.Local).AddTicks(7750)
                        },
                        new
                        {
                            AuthorId = 10,
                            AuthorName = "Rachelle Hayes",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2019, 3, 30, 18, 32, 21, 951, DateTimeKind.Local).AddTicks(3956),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 12, 27, 51, 545, DateTimeKind.Local).AddTicks(1273)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.DBModels.CompanionDbModel", b =>
                {
                    b.Property<int>("CompanionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("WhoPlayed")
                        .HasColumnType("int");

                    b.HasKey("CompanionId");

                    b.ToTable("Companions");

                    b.HasData(
                        new
                        {
                            CompanionId = 1,
                            CompanionName = "Tillman Zemlak",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 11, 5, 12, 39, 32, 562, DateTimeKind.Local).AddTicks(5367),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 17, 41, 25, 517, DateTimeKind.Local).AddTicks(3271),
                            WhoPlayed = 1
                        },
                        new
                        {
                            CompanionId = 2,
                            CompanionName = "Greyson Walker",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2018, 10, 26, 2, 10, 9, 93, DateTimeKind.Local).AddTicks(9495),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 3, 39, 24, 518, DateTimeKind.Local).AddTicks(4947),
                            WhoPlayed = 0
                        },
                        new
                        {
                            CompanionId = 3,
                            CompanionName = "Ursula Boyle",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 9, 14, 16, 6, 13, 339, DateTimeKind.Local).AddTicks(2087),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 17, 31, 55, 105, DateTimeKind.Local).AddTicks(9708),
                            WhoPlayed = 1
                        },
                        new
                        {
                            CompanionId = 4,
                            CompanionName = "Jameson Williamson",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 5, 26, 15, 41, 2, 761, DateTimeKind.Local).AddTicks(8927),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 13, 5, 27, 813, DateTimeKind.Local).AddTicks(6481),
                            WhoPlayed = 0
                        },
                        new
                        {
                            CompanionId = 5,
                            CompanionName = "Cyrus Berge",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 12, 16, 19, 58, 3, 721, DateTimeKind.Local).AddTicks(7954),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 17, 17, 36, 176, DateTimeKind.Local).AddTicks(7471),
                            WhoPlayed = 1
                        },
                        new
                        {
                            CompanionId = 6,
                            CompanionName = "Vicenta Bogan",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 12, 21, 14, 49, 10, 420, DateTimeKind.Local).AddTicks(1068),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 10, 25, 9, 645, DateTimeKind.Local).AddTicks(9924),
                            WhoPlayed = 0
                        },
                        new
                        {
                            CompanionId = 7,
                            CompanionName = "Cesar Tremblay",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 1, 2, 4, 52, 42, 670, DateTimeKind.Local).AddTicks(2167),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 2, 14, 33, 861, DateTimeKind.Local).AddTicks(9738),
                            WhoPlayed = 1
                        },
                        new
                        {
                            CompanionId = 8,
                            CompanionName = "Neha Kreiger",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 8, 15, 22, 53, 3, 553, DateTimeKind.Local).AddTicks(216),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 5, 29, 49, 313, DateTimeKind.Local).AddTicks(6696),
                            WhoPlayed = 0
                        },
                        new
                        {
                            CompanionId = 9,
                            CompanionName = "Modesta Terry",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 8, 26, 12, 14, 3, 104, DateTimeKind.Local).AddTicks(4436),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 18, 19, 16, 570, DateTimeKind.Local).AddTicks(4260),
                            WhoPlayed = 1
                        },
                        new
                        {
                            CompanionId = 10,
                            CompanionName = "Eddie McGlynn",
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2018, 4, 29, 17, 16, 36, 442, DateTimeKind.Local).AddTicks(5446),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 13, 9, 23, 901, DateTimeKind.Local).AddTicks(228),
                            WhoPlayed = 0
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.DBModels.DoctorDbModel", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstEpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastEpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Birthdate = new DateTime(2021, 8, 6, 8, 51, 47, 75, DateTimeKind.Local).AddTicks(8532),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 9, 28, 0, 17, 33, 604, DateTimeKind.Local).AddTicks(5829),
                            DoctorName = "Michael Fadel",
                            DoctorNumber = 2,
                            FirstEpisodeDate = new DateTime(2021, 8, 6, 16, 19, 34, 568, DateTimeKind.Local).AddTicks(5415),
                            LastEpisodeDate = new DateTime(2021, 8, 6, 15, 47, 34, 867, DateTimeKind.Local).AddTicks(8176),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 16, 30, 19, 98, DateTimeKind.Local).AddTicks(5737)
                        },
                        new
                        {
                            DoctorId = 2,
                            Birthdate = new DateTime(2021, 8, 5, 22, 30, 42, 231, DateTimeKind.Local).AddTicks(2321),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2018, 3, 14, 8, 37, 44, 531, DateTimeKind.Local).AddTicks(6692),
                            DoctorName = "Ralph Weimann",
                            DoctorNumber = 18,
                            FirstEpisodeDate = new DateTime(2021, 8, 6, 13, 6, 32, 605, DateTimeKind.Local).AddTicks(5274),
                            LastEpisodeDate = new DateTime(2021, 8, 5, 23, 25, 2, 32, DateTimeKind.Local).AddTicks(2241),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 19, 17, 46, 940, DateTimeKind.Local).AddTicks(2482)
                        },
                        new
                        {
                            DoctorId = 3,
                            Birthdate = new DateTime(2021, 8, 6, 2, 35, 32, 211, DateTimeKind.Local).AddTicks(9173),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2019, 12, 17, 4, 51, 17, 156, DateTimeKind.Local).AddTicks(6127),
                            DoctorName = "Audie Mosciski",
                            DoctorNumber = 9,
                            FirstEpisodeDate = new DateTime(2021, 8, 6, 18, 34, 23, 694, DateTimeKind.Local).AddTicks(575),
                            LastEpisodeDate = new DateTime(2021, 8, 6, 17, 50, 50, 555, DateTimeKind.Local).AddTicks(6256),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 10, 21, 20, 503, DateTimeKind.Local).AddTicks(3214)
                        },
                        new
                        {
                            DoctorId = 4,
                            Birthdate = new DateTime(2021, 8, 6, 16, 56, 49, 527, DateTimeKind.Local).AddTicks(1792),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 5, 10, 18, 4, 6, 867, DateTimeKind.Local).AddTicks(7717),
                            DoctorName = "Osbaldo Homenick",
                            DoctorNumber = 7,
                            FirstEpisodeDate = new DateTime(2021, 8, 6, 14, 33, 55, 701, DateTimeKind.Local).AddTicks(5825),
                            LastEpisodeDate = new DateTime(2021, 8, 6, 18, 57, 15, 33, DateTimeKind.Local).AddTicks(7174),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 4, 36, 40, 699, DateTimeKind.Local).AddTicks(5440)
                        },
                        new
                        {
                            DoctorId = 5,
                            Birthdate = new DateTime(2021, 8, 6, 7, 0, 11, 90, DateTimeKind.Local).AddTicks(3591),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 4, 7, 17, 15, 40, 489, DateTimeKind.Local).AddTicks(1012),
                            DoctorName = "Darien Murazik",
                            DoctorNumber = 12,
                            FirstEpisodeDate = new DateTime(2021, 8, 6, 11, 49, 44, 733, DateTimeKind.Local).AddTicks(1670),
                            LastEpisodeDate = new DateTime(2021, 8, 6, 1, 31, 27, 695, DateTimeKind.Local).AddTicks(2999),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 9, 42, 35, 852, DateTimeKind.Local).AddTicks(1902)
                        },
                        new
                        {
                            DoctorId = 6,
                            Birthdate = new DateTime(2021, 8, 6, 19, 12, 6, 617, DateTimeKind.Local).AddTicks(3811),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2016, 10, 26, 1, 48, 25, 719, DateTimeKind.Local).AddTicks(9254),
                            DoctorName = "Curtis Little",
                            DoctorNumber = 3,
                            FirstEpisodeDate = new DateTime(2021, 8, 5, 20, 54, 50, 292, DateTimeKind.Local).AddTicks(6629),
                            LastEpisodeDate = new DateTime(2021, 8, 6, 0, 42, 32, 538, DateTimeKind.Local).AddTicks(1788),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 7, 41, 32, 693, DateTimeKind.Local).AddTicks(9317)
                        },
                        new
                        {
                            DoctorId = 7,
                            Birthdate = new DateTime(2021, 8, 6, 5, 25, 54, 145, DateTimeKind.Local).AddTicks(661),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 3, 6, 19, 55, 47, 61, DateTimeKind.Local).AddTicks(1584),
                            DoctorName = "Easter Homenick",
                            DoctorNumber = 4,
                            FirstEpisodeDate = new DateTime(2021, 8, 6, 14, 47, 43, 648, DateTimeKind.Local).AddTicks(178),
                            LastEpisodeDate = new DateTime(2021, 8, 5, 21, 4, 59, 401, DateTimeKind.Local).AddTicks(2522),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 21, 51, 29, 952, DateTimeKind.Local).AddTicks(6923)
                        },
                        new
                        {
                            DoctorId = 8,
                            Birthdate = new DateTime(2021, 8, 6, 2, 58, 52, 452, DateTimeKind.Local).AddTicks(4600),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2019, 2, 20, 14, 22, 48, 810, DateTimeKind.Local).AddTicks(1314),
                            DoctorName = "Darron Barton",
                            DoctorNumber = 11,
                            FirstEpisodeDate = new DateTime(2021, 8, 6, 14, 55, 40, 568, DateTimeKind.Local).AddTicks(5083),
                            LastEpisodeDate = new DateTime(2021, 8, 5, 22, 2, 20, 20, DateTimeKind.Local).AddTicks(6155),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 9, 43, 43, 651, DateTimeKind.Local).AddTicks(3827)
                        },
                        new
                        {
                            DoctorId = 9,
                            Birthdate = new DateTime(2021, 8, 5, 22, 12, 57, 676, DateTimeKind.Local).AddTicks(9865),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 4, 26, 20, 25, 9, 873, DateTimeKind.Local).AddTicks(2903),
                            DoctorName = "Ronaldo Bayer",
                            DoctorNumber = 5,
                            FirstEpisodeDate = new DateTime(2021, 8, 6, 17, 17, 38, 643, DateTimeKind.Local).AddTicks(8583),
                            LastEpisodeDate = new DateTime(2021, 8, 6, 6, 34, 6, 370, DateTimeKind.Local).AddTicks(7573),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 2, 21, 37, 45, DateTimeKind.Local).AddTicks(8890)
                        },
                        new
                        {
                            DoctorId = 10,
                            Birthdate = new DateTime(2021, 8, 5, 21, 44, 6, 681, DateTimeKind.Local).AddTicks(9525),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 11, 27, 15, 42, 36, 14, DateTimeKind.Local).AddTicks(6590),
                            DoctorName = "Elyse Cassin",
                            DoctorNumber = 7,
                            FirstEpisodeDate = new DateTime(2021, 8, 6, 18, 20, 53, 146, DateTimeKind.Local).AddTicks(5166),
                            LastEpisodeDate = new DateTime(2021, 8, 5, 23, 28, 15, 933, DateTimeKind.Local).AddTicks(1538),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 12, 7, 28, 647, DateTimeKind.Local).AddTicks(1255)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.DBModels.EnemyDbModel", b =>
                {
                    b.Property<int>("EnemyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnemyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("EnemyId");

                    b.ToTable("Enemies");

                    b.HasData(
                        new
                        {
                            EnemyId = 1,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2016, 11, 18, 5, 2, 39, 192, DateTimeKind.Local).AddTicks(1672),
                            Description = "Et eligendi aspernatur quis. Repellat molestias vitae occaecati aut sunt. Officia autem repellat fugiat magni at autem dolores vero qui.",
                            EnemyName = "Brain Stanton",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 9, 5, 46, 587, DateTimeKind.Local).AddTicks(9255)
                        },
                        new
                        {
                            EnemyId = 2,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2018, 6, 24, 2, 18, 27, 666, DateTimeKind.Local).AddTicks(3621),
                            Description = "Quaerat est sapiente soluta ratione aspernatur nesciunt dolorem placeat at. Rerum iusto nulla sed aut illum sint ipsa. Quisquam sit iste occaecati illum ut et.",
                            EnemyName = "Kobe Heller",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 12, 54, 40, 288, DateTimeKind.Local).AddTicks(160)
                        },
                        new
                        {
                            EnemyId = 3,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 3, 30, 12, 3, 44, 101, DateTimeKind.Local).AddTicks(9466),
                            Description = "Dolore ipsa non quod eveniet quia voluptas. Doloribus quo voluptas quae ratione sed sit quam provident. Placeat consequatur quia aut distinctio dolore molestiae illo odio eos.",
                            EnemyName = "Taya Miller",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 1, 52, 24, 124, DateTimeKind.Local).AddTicks(1385)
                        },
                        new
                        {
                            EnemyId = 4,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2018, 2, 18, 17, 8, 33, 87, DateTimeKind.Local).AddTicks(2519),
                            Description = "Nam quis eum ut voluptates aut. Doloribus aut illo illo maxime a quis voluptate. Harum vel ut et id. Ea dignissimos vel. Vel nulla soluta reiciendis rerum.",
                            EnemyName = "Gilda Gaylord",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 7, 1, 58, 900, DateTimeKind.Local).AddTicks(2092)
                        },
                        new
                        {
                            EnemyId = 5,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2018, 3, 24, 8, 29, 14, 73, DateTimeKind.Local).AddTicks(703),
                            Description = "Eos qui veniam excepturi molestiae quia. Doloremque sequi facere repudiandae quis rerum facilis quia incidunt. Harum delectus officiis. Molestiae earum cupiditate et nostrum autem enim.",
                            EnemyName = "Zena Brekke",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 3, 46, 48, 710, DateTimeKind.Local).AddTicks(4185)
                        },
                        new
                        {
                            EnemyId = 6,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2019, 12, 2, 6, 4, 49, 729, DateTimeKind.Local).AddTicks(7658),
                            Description = "Libero et unde et aliquid corporis. Nostrum nulla quae quia est laudantium asperiores. Velit natus placeat nulla. Nostrum esse temporibus recusandae aut omnis aut eos provident. Aperiam ipsa dicta nihil dolorum minus.",
                            EnemyName = "Ayana Mraz",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 13, 28, 5, 33, DateTimeKind.Local).AddTicks(4016)
                        },
                        new
                        {
                            EnemyId = 7,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 3, 5, 4, 5, 26, 27, DateTimeKind.Local).AddTicks(2862),
                            Description = "Sunt tempore accusantium ut quisquam magnam inventore quidem fugit. Placeat dolore voluptatem et sed magnam sed. Dolorum deserunt quam ea omnis in perferendis. Animi ipsa quis odio. Itaque officiis ab. Et reprehenderit magnam non et cumque dolore voluptatem.",
                            EnemyName = "Tre Powlowski",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 20, 33, 23, 776, DateTimeKind.Local).AddTicks(1161)
                        },
                        new
                        {
                            EnemyId = 8,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2019, 2, 1, 19, 25, 51, 49, DateTimeKind.Local).AddTicks(2402),
                            Description = "Dolor modi consequatur et atque alias quis autem est. Fuga cupiditate natus est sit voluptatem cum dolores vel autem. Et qui vero et. Doloribus necessitatibus ipsum vel dolorem nihil. Vel nihil illum alias. Et itaque qui tempore reiciendis nihil voluptas est est.",
                            EnemyName = "William Pfannerstill",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 8, 29, 47, 923, DateTimeKind.Local).AddTicks(4819)
                        },
                        new
                        {
                            EnemyId = 9,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 7, 17, 4, 41, 28, 48, DateTimeKind.Local).AddTicks(433),
                            Description = "Odio aut velit similique itaque. Molestias placeat vitae aut in sed nemo dicta. Exercitationem sit tempora velit quaerat at debitis officiis temporibus ut. Debitis sunt qui facere aut. Amet eaque eum qui. Vel atque dolor quos quasi sed non amet rem.",
                            EnemyName = "Margarett Mueller",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 10, 21, 59, 825, DateTimeKind.Local).AddTicks(5822)
                        },
                        new
                        {
                            EnemyId = 10,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 7, 17, 17, 58, 39, 496, DateTimeKind.Local).AddTicks(8201),
                            Description = "Totam possimus atque est quos natus. Dolorum doloremque cum. Quam est voluptas alias adipisci sit enim cumque aspernatur. Quis quod sit voluptas dolor nisi. Id quasi deserunt aliquam dolore quo veniam aliquam porro praesentium. Dolorem vel adipisci repellendus consequatur quam architecto.",
                            EnemyName = "Jalen DuBuque",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 0, 12, 55, 471, DateTimeKind.Local).AddTicks(4273)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.DBModels.EpisodeDbModel", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("EpisodeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EpisodeId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            EpisodeId = 1,
                            AuthorId = 4,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 4, 16, 16, 56, 34, 566, DateTimeKind.Local).AddTicks(7477),
                            DoctorId = 9,
                            EpisodeDate = new DateTime(2021, 8, 6, 7, 9, 52, 331, DateTimeKind.Local).AddTicks(8505),
                            EpisodeNumber = 2,
                            EpisodeType = "Et quia deleniti rerum odit sed voluptatem et.",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 23, 46, 44, 567, DateTimeKind.Local).AddTicks(8940),
                            Notes = "Voluptas amet labore magnam et quo. Placeat quia dolorem quisquam repudiandae ut similique. Dolor sint eveniet cum. Laudantium nam excepturi.\n\nUt reprehenderit vitae ipsa velit nisi eveniet ipsum cum. Vero molestias modi illo. Enim sed aut voluptas numquam est temporibus facere aut voluptas.\n\nExcepturi quis aperiam aspernatur cum neque iure incidunt. Cupiditate nihil voluptas deleniti dolorem quod. Iusto nemo tempore exercitationem.",
                            SeriesNumber = 1,
                            Title = "Eligendi voluptatem eos sit est et amet."
                        },
                        new
                        {
                            EpisodeId = 2,
                            AuthorId = 2,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 1, 21, 14, 18, 20, 930, DateTimeKind.Local).AddTicks(5316),
                            DoctorId = 8,
                            EpisodeDate = new DateTime(2021, 8, 6, 15, 47, 57, 518, DateTimeKind.Local).AddTicks(1174),
                            EpisodeNumber = 12,
                            EpisodeType = "Voluptates quis saepe non.",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 15, 37, 46, 941, DateTimeKind.Local).AddTicks(6572),
                            Notes = "Iure hic natus voluptatem libero. Quibusdam officiis quisquam excepturi. Perspiciatis non ullam. Facere aut esse quas.\n\nOdio at qui in consequuntur voluptas praesentium voluptatem nisi. Aspernatur quia laudantium. Modi et voluptatem odio aperiam occaecati. Nam autem sed corrupti magnam quae dolorum quasi quidem.\n\nUt iusto hic explicabo reiciendis. Ut voluptas laboriosam pariatur autem atque aut laboriosam laudantium qui. Eum corrupti aut totam molestiae sunt est deleniti quae voluptates. Minima voluptas hic impedit optio assumenda nemo accusantium cupiditate.",
                            SeriesNumber = 5,
                            Title = "Aperiam sit nisi fugiat qui dignissimos placeat eum."
                        },
                        new
                        {
                            EpisodeId = 3,
                            AuthorId = 7,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 1, 31, 21, 51, 24, 958, DateTimeKind.Local).AddTicks(8080),
                            DoctorId = 4,
                            EpisodeDate = new DateTime(2021, 8, 6, 14, 51, 54, 376, DateTimeKind.Local).AddTicks(2839),
                            EpisodeNumber = 3,
                            EpisodeType = "Officiis ut ut adipisci sint.",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 4, 27, 12, 236, DateTimeKind.Local).AddTicks(9327),
                            Notes = "Nisi dolor et non consequatur libero natus et eveniet libero. Labore aperiam odio ullam et necessitatibus vitae architecto enim. Sit atque officia occaecati omnis dicta illo non. Iste laboriosam voluptates sit nobis ut excepturi perferendis. Incidunt harum soluta aut dolorum odit. Sed ut molestiae omnis aliquid.\n\nOfficia incidunt nesciunt eligendi doloremque. Dolore qui molestias quis consectetur fugit. Voluptas cumque possimus hic ex officiis.\n\nRerum veritatis quia et deleniti incidunt facilis id consequuntur. Ea corrupti inventore quia aspernatur cupiditate. Deleniti id voluptatem est quia qui illum molestias. Sapiente esse deserunt reiciendis voluptate deleniti vel odio. Ipsum maiores dolorem unde dolor animi nulla vel quo fugiat.",
                            SeriesNumber = 2,
                            Title = "Et labore voluptatem ea."
                        },
                        new
                        {
                            EpisodeId = 4,
                            AuthorId = 1,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2018, 9, 4, 1, 8, 47, 478, DateTimeKind.Local).AddTicks(6158),
                            DoctorId = 7,
                            EpisodeDate = new DateTime(2021, 8, 6, 17, 34, 11, 114, DateTimeKind.Local).AddTicks(8555),
                            EpisodeNumber = 7,
                            EpisodeType = "Et exercitationem nihil cupiditate quis.",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 10, 4, 56, 818, DateTimeKind.Local).AddTicks(5663),
                            Notes = "Aut et autem molestiae sed eum non molestiae unde aut. Natus maiores aut enim tenetur consequatur ea soluta. Non quo et et quas et totam.\n\nAutem cumque incidunt autem tenetur excepturi assumenda harum soluta optio. Earum voluptas asperiores reprehenderit est odit. Voluptatum perspiciatis ipsam quam repellendus. Excepturi nam enim autem rerum nihil. Commodi velit occaecati quia aut sint voluptas aperiam quis quas.\n\nNam numquam officia quis. Pariatur expedita qui quaerat doloribus amet deserunt a repudiandae. Veniam quis et qui est quaerat repellendus aut quod. Qui quis quaerat nisi suscipit.",
                            SeriesNumber = 5,
                            Title = "Illum enim tempora ratione voluptatem."
                        },
                        new
                        {
                            EpisodeId = 5,
                            AuthorId = 6,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 4, 19, 14, 13, 32, 571, DateTimeKind.Local).AddTicks(9580),
                            DoctorId = 10,
                            EpisodeDate = new DateTime(2021, 8, 6, 2, 51, 49, 35, DateTimeKind.Local).AddTicks(7976),
                            EpisodeNumber = 19,
                            EpisodeType = "Libero optio quia est et omnis tenetur qui aut.",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 8, 42, 44, 133, DateTimeKind.Local).AddTicks(5606),
                            Notes = "Magni odit quidem officiis debitis aut pariatur illo. Natus in illo. Aut qui animi libero autem molestias ea asperiores illum accusamus. Incidunt eos qui qui qui id.\n\nVero qui reiciendis itaque ea velit et. Architecto et qui delectus. Ut quisquam quos officiis voluptas unde qui dolore quia possimus.\n\nUt rerum quod eum. Expedita nihil praesentium. Velit nisi ut quia et aliquam omnis commodi quis placeat. Et excepturi voluptatem esse labore at.",
                            SeriesNumber = 1,
                            Title = "Perferendis molestiae numquam amet facere."
                        },
                        new
                        {
                            EpisodeId = 6,
                            AuthorId = 8,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 4, 13, 11, 45, 40, 924, DateTimeKind.Local).AddTicks(4892),
                            DoctorId = 2,
                            EpisodeDate = new DateTime(2021, 8, 6, 19, 16, 13, 256, DateTimeKind.Local).AddTicks(8223),
                            EpisodeNumber = 2,
                            EpisodeType = "Sed velit ipsa officia et consequatur dolorem sit.",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 19, 26, 10, 964, DateTimeKind.Local).AddTicks(3356),
                            Notes = "Est vel quia qui voluptatem. Quis facere quidem laudantium excepturi ut molestias. Atque ab id. Dolorem ducimus in sint corrupti. Est consectetur voluptatibus. Et autem saepe qui est commodi in reprehenderit quia.\n\nAsperiores id placeat ea nemo et aliquid sequi. Consequatur temporibus minima molestias quo ducimus recusandae quia necessitatibus quis. Architecto est est rerum voluptatem similique. Laudantium ratione quisquam sunt officiis maiores rerum quia. Est nesciunt sit ipsum exercitationem aperiam sit tenetur beatae.\n\nMaiores voluptas et consectetur quas necessitatibus. Et eum asperiores. Explicabo id quia necessitatibus aut et porro repudiandae exercitationem.",
                            SeriesNumber = 8,
                            Title = "Vel officia nam vitae nostrum voluptas aut quo consequatur."
                        },
                        new
                        {
                            EpisodeId = 7,
                            AuthorId = 4,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 9, 10, 10, 47, 3, 573, DateTimeKind.Local).AddTicks(5089),
                            DoctorId = 6,
                            EpisodeDate = new DateTime(2021, 8, 6, 9, 45, 36, 313, DateTimeKind.Local).AddTicks(5850),
                            EpisodeNumber = 1,
                            EpisodeType = "Repellat minus assumenda cupiditate aut.",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 23, 28, 16, 501, DateTimeKind.Local).AddTicks(9395),
                            Notes = "Repellat ea voluptatem est ut neque. Cupiditate quia est ratione qui autem est et sunt. Laboriosam illo molestiae iste totam facere exercitationem porro magni.\n\nQuo officiis facere et maiores voluptatem. Quibusdam sit illum. Facilis consequatur distinctio eum velit similique. Autem numquam earum blanditiis asperiores molestias. Dolores necessitatibus non est est inventore odit labore. Nobis ducimus ut est sequi.\n\nConsequuntur omnis reiciendis et voluptate natus saepe vitae. Qui voluptas suscipit quo corrupti. Debitis dolore voluptas at autem deserunt. Exercitationem possimus ipsam voluptate. Aut recusandae dignissimos et ut voluptatem error illum ut sit.",
                            SeriesNumber = 20,
                            Title = "Non officia maiores et accusantium temporibus pariatur repellendus."
                        },
                        new
                        {
                            EpisodeId = 8,
                            AuthorId = 6,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 7, 30, 23, 19, 48, 559, DateTimeKind.Local).AddTicks(1395),
                            DoctorId = 9,
                            EpisodeDate = new DateTime(2021, 8, 6, 12, 25, 20, 608, DateTimeKind.Local).AddTicks(4658),
                            EpisodeNumber = 5,
                            EpisodeType = "Est repudiandae odit omnis.",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 9, 1, 52, 675, DateTimeKind.Local).AddTicks(5795),
                            Notes = "Et ratione eveniet consequatur explicabo quasi voluptatem. Atque eos distinctio dignissimos ad vel ratione quo. Accusantium perspiciatis rerum fugit tempore. Est eaque non aut quas. Rerum autem reiciendis quia perferendis architecto ullam velit consectetur. Cumque autem non illum quo inventore odio accusantium.\n\nQui sapiente velit et fugit dignissimos dolore repellendus ipsum assumenda. Sapiente facilis fugiat voluptas. Nobis sed quaerat. Pariatur nihil odit iure voluptas. Ut vero est nam animi et suscipit. Eligendi cum mollitia repudiandae non sunt dolorem.\n\nQuam voluptatum id qui. Aut facilis autem quia voluptas totam. Quisquam vero consequatur. Id ut reprehenderit dolores. Ipsum quaerat et inventore qui dolorem rem.",
                            SeriesNumber = 4,
                            Title = "Aut corporis sequi inventore voluptatibus quaerat modi est."
                        },
                        new
                        {
                            EpisodeId = 9,
                            AuthorId = 5,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 7, 24, 18, 58, 35, 560, DateTimeKind.Local).AddTicks(3466),
                            DoctorId = 10,
                            EpisodeDate = new DateTime(2021, 8, 6, 6, 2, 38, 830, DateTimeKind.Local).AddTicks(1547),
                            EpisodeNumber = 9,
                            EpisodeType = "Possimus quas qui ut eum quis.",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 28, 20, 21, 46, 51, DateTimeKind.Local).AddTicks(5261),
                            Notes = "Ut qui repellendus eligendi id doloremque iusto. Minus dolore numquam aut tempore ut. Quia id esse beatae maiores minus ut ipsum eveniet. Eum sit molestias. Modi saepe quia omnis. Ipsum ut nobis beatae corporis distinctio quae.\n\nOdio optio asperiores odit quis architecto. Soluta eos veritatis debitis temporibus molestiae est rerum in. Aut molestiae dolore excepturi ex explicabo ut eos veritatis. Quos cupiditate fugit esse earum est. Qui sed quia. Qui iusto corporis ut aperiam veritatis aut maxime.\n\nQuibusdam quas non et sed quo itaque dicta. Est delectus modi laborum suscipit sequi placeat. Itaque sit suscipit et nobis qui illo minima. Earum ut voluptatem aperiam laudantium qui. Voluptas eligendi voluptatem officia voluptas.",
                            SeriesNumber = 8,
                            Title = "Quis ad eos."
                        },
                        new
                        {
                            EpisodeId = 10,
                            AuthorId = 4,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 12, 7, 10, 33, 15, 845, DateTimeKind.Local).AddTicks(2967),
                            DoctorId = 3,
                            EpisodeDate = new DateTime(2021, 8, 5, 21, 2, 42, 163, DateTimeKind.Local).AddTicks(2040),
                            EpisodeNumber = 7,
                            EpisodeType = "Quo similique culpa.",
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 9, 29, 14, 24, 32, 863, DateTimeKind.Local).AddTicks(3346),
                            Notes = "Similique sit sunt et pariatur rerum dolores neque aut. Tenetur dolor ad. Voluptatibus ullam omnis. Ut officia aperiam et sint libero repudiandae doloribus. Delectus fugit qui velit nostrum consectetur debitis. Nostrum sit animi.\n\nMagnam quia provident fugiat est. Et doloremque quasi quia. A et vel minus tenetur nam et. Vero inventore dolorem quae corrupti repudiandae distinctio maiores in illo. Fugit quia optio rerum suscipit voluptates vitae nobis. Soluta corrupti omnis eveniet itaque et labore quos vel ratione.\n\nMinima est fugit enim vitae architecto quae. Aut et aut aut vel inventore quam voluptatem nesciunt ipsa. Accusamus voluptatibus aut enim consequatur quas enim aut est.",
                            SeriesNumber = 7,
                            Title = "Voluptate omnis fugit illo rem quis fuga assumenda."
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Domain.EpisodeDetails", b =>
                {
                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanionsNames")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Companions");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnemiesNames")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Enemies");

                    b.Property<DateTime?>("EpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("EpisodeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("viewEpisodes");
                });

            modelBuilder.Entity("EpisodeCompanion", b =>
                {
                    b.Property<int>("EpisodeCompanionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanionsCompanionId")
                        .HasColumnType("int")
                        .HasColumnName("CompanionId");

                    b.Property<int>("EpisodesEpisodeId")
                        .HasColumnType("int")
                        .HasColumnName("EpisodeId");

                    b.HasKey("EpisodeCompanionId");

                    b.HasIndex("CompanionsCompanionId");

                    b.HasIndex("EpisodesEpisodeId");

                    b.ToTable("EpisodeCompanion");

                    b.HasData(
                        new
                        {
                            EpisodeCompanionId = 1,
                            CompanionsCompanionId = 1,
                            EpisodesEpisodeId = 9
                        },
                        new
                        {
                            EpisodeCompanionId = 2,
                            CompanionsCompanionId = 8,
                            EpisodesEpisodeId = 8
                        },
                        new
                        {
                            EpisodeCompanionId = 3,
                            CompanionsCompanionId = 4,
                            EpisodesEpisodeId = 5
                        },
                        new
                        {
                            EpisodeCompanionId = 4,
                            CompanionsCompanionId = 6,
                            EpisodesEpisodeId = 6
                        },
                        new
                        {
                            EpisodeCompanionId = 5,
                            CompanionsCompanionId = 4,
                            EpisodesEpisodeId = 9
                        },
                        new
                        {
                            EpisodeCompanionId = 6,
                            CompanionsCompanionId = 4,
                            EpisodesEpisodeId = 10
                        },
                        new
                        {
                            EpisodeCompanionId = 7,
                            CompanionsCompanionId = 4,
                            EpisodesEpisodeId = 8
                        },
                        new
                        {
                            EpisodeCompanionId = 8,
                            CompanionsCompanionId = 7,
                            EpisodesEpisodeId = 3
                        },
                        new
                        {
                            EpisodeCompanionId = 9,
                            CompanionsCompanionId = 3,
                            EpisodesEpisodeId = 3
                        },
                        new
                        {
                            EpisodeCompanionId = 10,
                            CompanionsCompanionId = 2,
                            EpisodesEpisodeId = 8
                        });
                });

            modelBuilder.Entity("EpisodeEnemy", b =>
                {
                    b.Property<int>("EpisodeEnemyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EnemiesEnemyId")
                        .HasColumnType("int")
                        .HasColumnName("EnemyId");

                    b.Property<int>("EpisodesEpisodeId")
                        .HasColumnType("int")
                        .HasColumnName("EpisodeId");

                    b.HasKey("EpisodeEnemyId");

                    b.HasIndex("EnemiesEnemyId");

                    b.HasIndex("EpisodesEpisodeId");

                    b.ToTable("EpisodeEnemy");

                    b.HasData(
                        new
                        {
                            EpisodeEnemyId = 1,
                            EnemiesEnemyId = 10,
                            EpisodesEpisodeId = 9
                        },
                        new
                        {
                            EpisodeEnemyId = 2,
                            EnemiesEnemyId = 3,
                            EpisodesEpisodeId = 4
                        },
                        new
                        {
                            EpisodeEnemyId = 3,
                            EnemiesEnemyId = 1,
                            EpisodesEpisodeId = 10
                        },
                        new
                        {
                            EpisodeEnemyId = 4,
                            EnemiesEnemyId = 3,
                            EpisodesEpisodeId = 9
                        },
                        new
                        {
                            EpisodeEnemyId = 5,
                            EnemiesEnemyId = 5,
                            EpisodesEpisodeId = 4
                        },
                        new
                        {
                            EpisodeEnemyId = 6,
                            EnemiesEnemyId = 7,
                            EpisodesEpisodeId = 9
                        },
                        new
                        {
                            EpisodeEnemyId = 7,
                            EnemiesEnemyId = 8,
                            EpisodesEpisodeId = 8
                        },
                        new
                        {
                            EpisodeEnemyId = 8,
                            EnemiesEnemyId = 9,
                            EpisodesEpisodeId = 10
                        },
                        new
                        {
                            EpisodeEnemyId = 9,
                            EnemiesEnemyId = 3,
                            EpisodesEpisodeId = 3
                        },
                        new
                        {
                            EpisodeEnemyId = 10,
                            EnemiesEnemyId = 2,
                            EpisodesEpisodeId = 9
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.DBModels.EpisodeDbModel", b =>
                {
                    b.HasOne("DoctorWho.Db.DBModels.AuthorDbModel", "Author")
                        .WithMany("Episodes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorWho.Db.DBModels.DoctorDbModel", "Doctor")
                        .WithMany("Episodes")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("EpisodeCompanion", b =>
                {
                    b.HasOne("DoctorWho.Db.DBModels.CompanionDbModel", null)
                        .WithMany()
                        .HasForeignKey("CompanionsCompanionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorWho.Db.DBModels.EpisodeDbModel", null)
                        .WithMany()
                        .HasForeignKey("EpisodesEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EpisodeEnemy", b =>
                {
                    b.HasOne("DoctorWho.Db.DBModels.EnemyDbModel", null)
                        .WithMany()
                        .HasForeignKey("EnemiesEnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorWho.Db.DBModels.EpisodeDbModel", null)
                        .WithMany()
                        .HasForeignKey("EpisodesEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoctorWho.Db.DBModels.AuthorDbModel", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("DoctorWho.Db.DBModels.DoctorDbModel", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
