// <auto-generated />
using System;
using DoctorWho.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoctorWho.Db.Migrations.AccessRequestDb
{
    [DbContext(typeof(AccessRequestDbContext))]
    [Migration("20210930145003_seed_data_with_metadata")]
    partial class seed_data_with_metadata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoctorWho.Db.Access.AccessRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("AccessRequests");

                    b.HasData(
                        new
                        {
                            RequestId = 1000,
                            AccessLevel = 4,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2012, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UserId = "admin"
                        },
                        new
                        {
                            RequestId = 1001,
                            AccessLevel = 1,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UserId = "redacted-user"
                        },
                        new
                        {
                            RequestId = 1002,
                            AccessLevel = 2,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2005, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            ModifiedBy = "admin",
                            ModifiedOn = new DateTime(2018, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UserId = "partial-user"
                        },
                        new
                        {
                            RequestId = 1003,
                            AccessLevel = 4,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2004, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2005, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UserId = "modify-user"
                        },
                        new
                        {
                            RequestId = 1004,
                            AccessLevel = 3,
                            CreatedBy = "modify-user",
                            CreatedOn = new DateTime(2014, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UserId = "approve-user"
                        },
                        new
                        {
                            RequestId = 100,
                            AccessLevel = 2,
                            CreatedBy = "modify-user",
                            CreatedOn = new DateTime(2018, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "admin",
                            ModifiedOn = new DateTime(2021, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            UserId = "testing-user"
                        },
                        new
                        {
                            RequestId = 101,
                            AccessLevel = 2,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2002, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UserId = "testing-user"
                        },
                        new
                        {
                            RequestId = 102,
                            AccessLevel = 2,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2004, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2006, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2019, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            UserId = "testing-user"
                        },
                        new
                        {
                            RequestId = 103,
                            AccessLevel = 2,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2017, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "admin",
                            ModifiedOn = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2021, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            UserId = "testing-user"
                        },
                        new
                        {
                            RequestId = 104,
                            AccessLevel = 2,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            UserId = "testing-user"
                        },
                        new
                        {
                            RequestId = 2000,
                            AccessLevel = 2,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2016, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "modify-user",
                            ModifiedOn = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            UserId = "approved-user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
